require: rubocop-rspec
AllCops:
  Exclude:
    - 'test/fixtures/cookbooks/**/*'
    - 'test/integration/**/*'
    - 'vendor/**/*'
Lint/UnifiedInteger:
  Enabled: false
Metrics/BlockLength:
  ExcludedMethods: ['describe', 'context']
