branches:
  only:
    - master

language: ruby
cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - gem --version
matrix:
  include:
    - rvm: 2.4.1
      script:
        - bundle exec rubocop
        - bundle exec rspec
