env:
  DOCKER_COMPOSE_VERSION: 1.14.0

sudo: required

language: ruby

services:
  - docker

before_install:
  - sudo apt-get update
  - sudo rm /usr/local/bin/docker-compose
  - curl -L https://github.com/docker/compose/releases/download/${DOCKER_COMPOSE_VERSION}/docker-compose-`uname -s`-`uname -m` > docker-compose
  - chmod +x docker-compose
  - sudo mv docker-compose /usr/local/bin

branches:
  only:
    - master

cache: bundler
before_install:
  - gem update --system
  - gem update bundler
  - gem --version

matrix:
  include:
    - rvm: 2.4.1
      script:
        - bundle exec rubocop
        - bundle exec rspec
